[test]
# Enable coverage reporting
coverage = false

coveragePathIgnorePatterns = [
  "**/test/**",
  "**/db/**",
  'src/lib/server/api/logger.ts',
  'src/lib/server/api/utils/exceptions.ts',
]

# Test timeout in milliseconds
timeout = 10000

# Environment variables for tests
env = [
  "NODE_ENV=test",
  "DATABASE_URL=postgresql://test:test@localhost:5432/test"
]

# Preload modules for tests
preload = ["./src/lib/server/test/env-plugin.ts", "./src/lib/server/test/setup.ts"] 
